<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        DB::table('countries')->delete();

        DB::table('countries')->insert(array(
            0 => array(
                'id' => 1,
                'name' => 'Afghanistan',
                'iso3' => 'AFG',
                'iso2' => 'AF',
                'callcode' => '93',
                'currency' => 'AFN',
                'flag' => '🇦🇫',
            ),
            1 => [
                'id' => 2,
                'name' => 'Aland Islands',
                'iso3' => 'ALA',
                'iso2' => 'AX',
                'callcode' => '+358-18',
                'currency' => 'EUR',
                'flag' => '🇦🇽',
            ],
            2 => [
                'id' => 3,
                'name' => 'Albania',
                'iso3' => 'ALB',
                'iso2' => 'AL',
                'callcode' => '+355',
                'currency' => 'ALL',
                'flag' => '🇦🇱',
            ],
            3 => [
                'id' => 4,
                'name' => 'Algeria',
                'iso3' => 'DZA',
                'iso2' => 'DZ',
                'callcode' => '+213',
                'currency' => 'DZD',
                'flag' => '🇩🇿',
            ],
            4 => [
                'id' => 5,
                'name' => 'Andorra',
                'iso3' => 'AND',
                'iso2' => 'AD',
                'callcode' => '+376',
                'currency' => 'EUR',
                'flag' => '🇦🇩',
            ],
            5 => [
                'id' => 6,
                'name' => 'Angola',
                'iso3' => 'AGO',
                'iso2' => 'AO',
                'callcode' => '+244',
                'currency' => 'AOA',
                'flag' => '🇦🇴',
            ],
            6 => [
                'id' => 7,
                'name' => 'Anguilla',
                'iso3' => 'AIA',
                'iso2' => 'AI',
                'callcode' => '+1-264',
                'currency' => 'XCD',
                'flag' => '🇦🇮',
            ],
            7 => [
                'id' => 8,
                'name' => 'Antarctica',
                'iso3' => 'ATA',
                'iso2' => 'AQ',
                'callcode' => '+672',
                'currency' => '',
                'flag' => '🇦🇶',
            ],
            8 => [
                'id' => 9,
                'name' => 'Antigua and Barbuda',
                'iso3' => 'ATG',
                'iso2' => 'AG',
                'callcode' => '+1-268',
                'currency' => 'XCD',
                'flag' => '🇦🇬',
            ],
            9 => [
                'id' => 10,
                'name' => 'Argentina',
                'iso3' => 'ARG',
                'iso2' => 'AR',
                'callcode' => '+54',
                'currency' => 'ARS',
                'flag' => '🇦🇷',
            ],
            10 => [
                'id' => 11,
                'name' => 'Armenia',
                'iso3' => 'ARM',
                'iso2' => 'AM',
                'callcode' => '+374',
                'currency' => 'AMD',
                'flag' => '🇦🇲',
            ],
            11 => [
                'id' => 12,
                'name' => 'Aruba',
                'iso3' => 'ABW',
                'iso2' => 'AW',
                'callcode' => '+297',
                'currency' => 'AWG',
                'flag' => '🇦🇼',
            ],
            12 => [
                'id' => 13,
                'name' => 'Australia',
                'iso3' => 'AUS',
                'iso2' => 'AU',
                'callcode' => '+61',
                'currency' => 'AUD',
                'flag' => '🇦🇺',
            ],
            13 => [
                'id' => 14,
                'name' => 'Austria',
                'iso3' => 'AUT',
                'iso2' => 'AT',
                'callcode' => '+43',
                'currency' => 'EUR',
                'flag' => '🇦🇹',
            ],
            14 => [
                'id' => 15,
                'name' => 'Azerbaijan',
                'iso3' => 'AZE',
                'iso2' => 'AZ',
                'callcode' => '+994',
                'currency' => 'AZN',
                'flag' => '🇦🇿',
            ],
            15 => [
                'id' => 16,
                'name' => 'Bahamas The',
                'iso3' => 'BHS',
                'iso2' => 'BS',
                'callcode' => '+1-242',
                'currency' => 'BSD',
                'flag' => '🇧🇸',
            ],
            16 => [
                'id' => 17,
                'name' => 'Bahrain',
                'iso3' => 'BHR',
                'iso2' => 'BH',
                'callcode' => '+973',
                'currency' => 'BHD',
                'flag' => '🇧🇭',
            ],
            17 => [
                'id' => 18,
                'name' => 'Bangladesh',
                'iso3' => 'BGD',
                'iso2' => 'BD',
                'callcode' => '+880',
                'currency' => 'BDT',
                'flag' => '🇧🇩',
            ],
            18 => [
                'id' => 19,
                'name' => 'Barbados',
                'iso3' => 'BRB',
                'iso2' => 'BB',
                'callcode' => '+1-246',
                'currency' => 'BBD',
                'flag' => '🇧🇧',
            ],
            19 => [
                'id' => 20,
                'name' => 'Belarus',
                'iso3' => 'BLR',
                'iso2' => 'BY',
                'callcode' => '+375',
                'currency' => 'BYN',
                'flag' => '🇧🇾',
            ],
            20 => [
                'id' => 21,
                'name' => 'Belgium',
                'iso3' => 'BEL',
                'iso2' => 'BE',
                'callcode' => '+32',
                'currency' => 'EUR',
                'flag' => '🇧🇪',
            ],
            21 => [
                'id' => 22,
                'name' => 'Belize',
                'iso3' => 'BLZ',
                'iso2' => 'BZ',
                'callcode' => '+501',
                'currency' => 'BZD',
                'flag' => '🇧🇿',
            ],
            22 => [
                'id' => 23,
                'name' => 'Benin',
                'iso3' => 'BEN',
                'iso2' => 'BJ',
                'callcode' => '+229',
                'currency' => 'XOF',
                'flag' => '🇧🇯',
            ],
            23 => [
                'id' => 24,
                'name' => 'Bermuda',
                'iso3' => 'BMU',
                'iso2' => 'BM',
                'callcode' => '+1-441',
                'currency' => 'BMD',
                'flag' => '🇧🇲',
            ],
            24 => [
                'id' => 25,
                'name' => 'Bhutan',
                'iso3' => 'BTN',
                'iso2' => 'BT',
                'callcode' => '+975',
                'currency' => 'BTN',
                'flag' => '🇧🇹',
            ],
            25 => [
                'id' => 26,
                'name' => 'Bolivia',
                'iso3' => 'BOL',
                'iso2' => 'BO',
                'callcode' => '+591',
                'currency' => 'BOB',
                'flag' => '🇧🇴',
            ],
            26 => [
                'id' => 27,
                'name' => 'Bosnia and Herzegovina',
                'iso3' => 'BIH',
                'iso2' => 'BA',
                'callcode' => '+387',
                'currency' => 'BAM',
                'flag' => '🇧🇦',
            ],
            27 => [
                'id' => 28,
                'name' => 'Botswana',
                'iso3' => 'BWA',
                'iso2' => 'BW',
                'callcode' => '+267',
                'currency' => 'BWP',
                'flag' => '🇧🇼',
            ],
            28 => [
                'id' => 29,
                'name' => 'Bouvet Island',
                'iso3' => 'BVT',
                'iso2' => 'BV',
                'callcode' => '+47',
                'currency' => 'NOK',
                'flag' => '🇧🇻',
            ],
            29 => [
                'id' => 30,
                'name' => 'Brazil',
                'iso3' => 'BRA',
                'iso2' => 'BR',
                'callcode' => '+55',
                'currency' => 'BRL',
                'flag' => '🇧🇷',
            ],
            31 => array(
                'id' => 32,
                'name' => 'Brunei',
                'iso3' => 'BRN',
                'iso2' => 'BN',
                'callcode' => '+673',
                'currency' => 'BND',
                'flag' => '🇧🇳',
            ),
            32 => array(
                'id' => 33,
                'name' => 'Bulgaria',
                'iso3' => 'BGR',
                'iso2' => 'BG',
                'callcode' => '+359',
                'currency' => 'BGN',
                'flag' => '🇧🇬',
            ),
            33 => array(
                'id' => 34,
                'name' => 'Burkina Faso',
                'iso3' => 'BFA',
                'iso2' => 'BF',
                'callcode' => '+226',
                'currency' => 'XOF',
                'flag' => '🇧🇫',
            ),
            34 => array(
                'id' => 35,
                'name' => 'Burundi',
                'iso3' => 'BDI',
                'iso2' => 'BI',
                'callcode' => '+257',
                'currency' => 'BIF',
                'flag' => '🇧🇮',
            ),
            35 => array(
                'id' => 36,
                'name' => 'Cambodia',
                'iso3' => 'KHM',
                'iso2' => 'KH',
                'callcode' => '+855',
                'currency' => 'KHR',
                'flag' => '🇰🇭',
            ),
            36 => array(
                'id' => 37,
                'name' => 'Cameroon',
                'iso3' => 'CMR',
                'iso2' => 'CM',
                'callcode' => '+237',
                'currency' => 'XAF',
                'flag' => '🇨🇲',
            ),
            37 => array(
                'id' => 38,
                'name' => 'Canada',
                'iso3' => 'CAN',
                'iso2' => 'CA',
                'callcode' => '+1',
                'currency' => 'CAD',
                'flag' => '🇨🇦',
            ),
            38 => array(
                'id' => 39,
                'name' => 'Cape Verde',
                'iso3' => 'CPV',
                'iso2' => 'CV',
                'callcode' => '+238',
                'currency' => 'CVE',
                'flag' => '🇨🇻',
            ),
            39 => array(
                'id' => 40,
                'name' => 'Cayman Islands',
                'iso3' => 'CYM',
                'iso2' => 'KY',
                'callcode' => '+1-345',
                'currency' => 'KYD',
                'flag' => '🇰🇾',
            ),
            40 => array(
                'id' => 41,
                'name' => 'Central African Republic',
                'iso3' => 'CAF',
                'iso2' => 'CF',
                'callcode' => '+236',
                'currency' => 'XAF',
                'flag' => '🇨🇫',
            ),
            41 => array(
                'id' => 42,
                'name' => 'Chad',
                'iso3' => 'TCD',
                'iso2' => 'TD',
                'callcode' => '+235',
                'currency' => 'XAF',
                'flag' => '🇹🇩',
            ),
            42 => array(
                'id' => 43,
                'name' => 'Chile',
                'iso3' => 'CHL',
                'iso2' => 'CL',
                'callcode' => '+56',
                'currency' => 'CLP',
                'flag' => '🇨🇱',
            ),
            43 => array(
                'id' => 44,
                'name' => 'China',
                'iso3' => 'CHN',
                'iso2' => 'CN',
                'callcode' => '+86',
                'currency' => 'CNY',
                'flag' => '🇨🇳',
            ),
            44 => array(
                'id' => 45,
                'name' => 'Christmas Island',
                'iso3' => 'CXR',
                'iso2' => 'CX',
                'callcode' => '+61',
                'currency' => 'AUD',
                'flag' => '🇨🇽',
            ),
            45 => array(
                'id' => 46,
                'name' => 'Cocos (Keeling) Islands',
                'iso3' => 'CCK',
                'iso2' => 'CC',
                'callcode' => '+61',
                'currency' => 'AUD',
                'flag' => '🇨🇨',
            ),
            46 => array(
                'id' => 47,
                'name' => 'Colombia',
                'iso3' => 'COL',
                'iso2' => 'CO',
                'callcode' => '+57',
                'currency' => 'COP',
                'flag' => '🇨🇴',
            ),
            47 => array(
                'id' => 48,
                'name' => 'Comoros',
                'iso3' => 'COM',
                'iso2' => 'KM',
                'callcode' => '+269',
                'currency' => 'KMF',
                'flag' => '🇰🇲',
            ),
            48 => array(
                'id' => 49,
                'name' => 'Congo',
                'iso3' => 'COG',
                'iso2' => 'CG',
                'callcode' => '+242',
                'currency' => 'XAF',
                'flag' => '🇨🇬',
            ),
            49 => array(
                'id' => 50,
                'name' => 'Congo The Democratic Republic Of The',
                'iso3' => 'COD',
                'iso2' => 'CD',
                'callcode' => '+243',
                'currency' => 'CDF',
                'flag' => '🇨🇩',
            ),
            50 => array(
                'id' => 51,
                'name' => 'Cook Islands',
                'iso3' => 'COK',
                'iso2' => 'CK',
                'callcode' => '+682',
                'currency' => 'NZD',
                'flag' => '🇨🇰',
            ),
            51 => array(
                'id' => 52,
                'name' => 'Costa Rica',
                'iso3' => 'CRI',
                'iso2' => 'CR',
                'callcode' => '+506',
                'currency' => 'CRC',
                'flag' => '🇨🇷',
            ),
            52 => array(
                'id' => 53,
                'name' => 'Cote D\'Ivoire (Ivory Coast)',
                'iso3' => 'CIV',
                'iso2' => 'CI',
                'callcode' => '+225',
                'currency' => 'XOF',
                'flag' => '🇨🇮',
            ),
            53 => array(
                'id' => 54,
                'name' => 'Croatia (Hrvatska)',
                'iso3' => 'HRV',
                'iso2' => 'HR',
                'callcode' => '+385',
                'currency' => 'HRK',
                'flag' => '🇭🇷',
            ),
            54 => array(
                'id' => 55,
                'name' => 'Cuba',
                'iso3' => 'CUB',
                'iso2' => 'CU',
                'callcode' => '+53',
                'currency' => 'CUP',
                'flag' => '🇨🇺',
            ),
            55 => array(
                'id' => 56,
                'name' => 'Cyprus',
                'iso3' => 'CYP',
                'iso2' => 'CY',
                'callcode' => '+357',
                'currency' => 'EUR',
                'flag' => '🇨🇾',
            ),
            56 => array(
                'id' => 57,
                'name' => 'Czech Republic',
                'iso3' => 'CZE',
                'iso2' => 'CZ',
                'callcode' => '+420',
                'currency' => 'CZK',
                'flag' => '🇨🇿',
            ),
            57 => array(
                'id' => 58,
                'name' => 'Denmark',
                'iso3' => 'DNK',
                'iso2' => 'DK',
                'callcode' => '+45',
                'currency' => 'DKK',
                'flag' => '🇩🇰',
            ),
            58 => array(
                'id' => 59,
                'name' => 'Djibouti',
                'iso3' => 'DJI',
                'iso2' => 'DJ',
                'callcode' => '+253',
                'currency' => 'DJF',
                'flag' => '🇩🇯',
            ),
            59 => array(
                'id' => 60,
                'name' => 'Dominica',
                'iso3' => 'DMA',
                'iso2' => 'DM',
                'callcode' => '+1-767',
                'currency' => 'XCD',
                'flag' => '🇩🇲',
            ),
            61 => array(
                'id' => 62,
                'name' => 'Dominican Republic',
                'iso3' => 'DOM',
                'iso2' => 'DO',
                'callcode' => '+1-809 and 1-829',
                'currency' => 'DOP',
                'flag' => '🇩🇴',
            ),
            62 => array(
                'id' => 63,
                'name' => 'East Timor',
                'iso3' => 'TLS',
                'iso2' => 'TL',
                'callcode' => '+670',
                'currency' => 'USD',
                'flag' => '🇹🇱',
            ),
            63 => array(
                'id' => 64,
                'name' => 'Ecuador',
                'iso3' => 'ECU',
                'iso2' => 'EC',
                'callcode' => '+593',
                'currency' => 'USD',
                'flag' => '🇪🇨',
            ),
            64 => array(
                'id' => 65,
                'name' => 'Egypt',
                'iso3' => 'EGY',
                'iso2' => 'EG',
                'callcode' => '+20',
                'currency' => 'EGP',
                'flag' => '🇪🇬',
            ),
            65 => array(
                'id' => 66,
                'name' => 'El Salvador',
                'iso3' => 'SLV',
                'iso2' => 'SV',
                'callcode' => '+503',
                'currency' => 'USD',
                'flag' => '🇸🇻',
            ),
            66 => array(
                'id' => 67,
                'name' => 'Equatorial Guinea',
                'iso3' => 'GNQ',
                'iso2' => 'GQ',
                'callcode' => '+240',
                'currency' => 'XAF',
                'flag' => '🇬🇶',
            ),
            67 => array(
                'id' => 68,
                'name' => 'Eritrea',
                'iso3' => 'ERI',
                'iso2' => 'ER',
                'callcode' => '+291',
                'currency' => 'ERN',
                'flag' => '🇪🇷',
            ),
            68 => array(
                'id' => 69,
                'name' => 'Estonia',
                'iso3' => 'EST',
                'iso2' => 'EE',
                'callcode' => '+372',
                'currency' => 'EUR',
                'flag' => '🇪🇪',
            ),
            69 => array(
                'id' => 70,
                'name' => 'Ethiopia',
                'iso3' => 'ETH',
                'iso2' => 'ET',
                'callcode' => '+251',
                'currency' => 'ETB',
                'flag' => '🇪🇹',
            ),
            70 => array(
                'id' => 71,
                'name' => 'Falkland Islands',
                'iso3' => 'FLK',
                'iso2' => 'FK',
                'callcode' => '+500',
                'currency' => 'FKP',
                'flag' => '🇫🇰',
            ),
            71 => array(
                'id' => 72,
                'name' => 'Faroe Islands',
                'iso3' => 'FRO',
                'iso2' => 'FO',
                'callcode' => '+298',
                'currency' => 'DKK',
                'flag' => '🇫🇴',
            ),
            72 => array(
                'id' => 73,
                'name' => 'Fiji Islands',
                'iso3' => 'FJI',
                'iso2' => 'FJ',
                'callcode' => '+679',
                'currency' => 'FJD',
                'flag' => '🇫🇯',
            ),
            73 => array(
                'id' => 74,
                'name' => 'Finland',
                'iso3' => 'FIN',
                'iso2' => 'FI',
                'callcode' => '+358',
                'currency' => 'EUR',
                'flag' => '🇫🇮',
            ),
            74 => array(
                'id' => 75,
                'name' => 'France',
                'iso3' => 'FRA',
                'iso2' => 'FR',
                'callcode' => '+33',
                'currency' => 'EUR',
                'flag' => '🇫🇷',
            ),
            75 => array(
                'id' => 76,
                'name' => 'French Guiana',
                'iso3' => 'GUF',
                'iso2' => 'GF',
                'callcode' => '+594',
                'currency' => 'EUR',
                'flag' => '🇬🇫',
            ),
            76 => array(
                'id' => 77,
                'name' => 'French Polynesia',
                'iso3' => 'PYF',
                'iso2' => 'PF',
                'callcode' => '+689',
                'currency' => 'XPF',
                'flag' => '🇵🇫',
            ),
            77 => array(
                'id' => 78,
                'name' => 'French Southern Territories',
                'iso3' => 'ATF',
                'iso2' => 'TF',
                'callcode' => '+262',
                'currency' => 'EUR',
                'flag' => '🇹🇫',
            ),
            78 => array(
                'id' => 79,
                'name' => 'Gabon',
                'iso3' => 'GAB',
                'iso2' => 'GA',
                'callcode' => '+241',
                'currency' => 'XAF',
                'flag' => '🇬🇦',
            ),
            79 => array(
                'id' => 80,
                'name' => 'Gambia The',
                'iso3' => 'GMB',
                'iso2' => 'GM',
                'callcode' => '+220',
                'currency' => 'GMD',
                'flag' => '🇬🇲',
            ),
            80 => array(
                'id' => 81,
                'name' => 'Georgia',
                'iso3' => 'GEO',
                'iso2' => 'GE',
                'callcode' => '+995',
                'currency' => 'GEL',
                'flag' => '🇬🇪',
            ),
            81 => array(
                'id' => 82,
                'name' => 'Germany',
                'iso3' => 'DEU',
                'iso2' => 'DE',
                'callcode' => '+49',
                'currency' => 'EUR',
                'flag' => '🇩🇪',
            ),
            82 => array(
                'id' => 83,
                'name' => 'Ghana',
                'iso3' => 'GHA',
                'iso2' => 'GH',
                'callcode' => '+233',
                'currency' => 'GHS',
                'flag' => '🇬🇭',
            ),
            83 => array(
                'id' => 84,
                'name' => 'Gibraltar',
                'iso3' => 'GIB',
                'iso2' => 'GI',
                'callcode' => '+350',
                'currency' => 'GIP',
                'flag' => '🇬🇮',
            ),
            84 => array(
                'id' => 85,
                'name' => 'Greece',
                'iso3' => 'GRC',
                'iso2' => 'GR',
                'callcode' => '+30',
                'currency' => 'EUR',
                'flag' => '🇬🇷',
            ),
            85 => array(
                'id' => 86,
                'name' => 'Greenland',
                'iso3' => 'GRL',
                'iso2' => 'GL',
                'callcode' => '+299',
                'currency' => 'DKK',
                'flag' => '🇬🇱',
            ),
            86 => array(
                'id' => 87,
                'name' => 'Grenada',
                'iso3' => 'GRD',
                'iso2' => 'GD',
                'callcode' => '+1-473',
                'currency' => 'XCD',
                'flag' => '🇬🇩',
            ),
            87 => array(
                'id' => 88,
                'name' => 'Guadeloupe',
                'iso3' => 'GLP',
                'iso2' => 'GP',
                'callcode' => '+590',
                'currency' => 'EUR',
                'flag' => '🇬🇵',
            ),
            88 => array(
                'id' => 89,
                'name' => 'Guam',
                'iso3' => 'GUM',
                'iso2' => 'GU',
                'callcode' => '+1-671',
                'currency' => 'USD',
                'flag' => '🇬🇺',
            ),
            89 => array(
                'id' => 90,
                'name' => 'Guatemala',
                'iso3' => 'GTM',
                'iso2' => 'GT',
                'callcode' => '+502',
                'currency' => 'GTQ',
                'flag' => '🇬🇹',
            ),
            90 => array(
                'id' => 91,
                'name' => 'Guernsey and Alderney',
                'iso3' => 'GGY',
                'iso2' => 'GG',
                'callcode' => '+44-1481',
                'currency' => 'GBP',
                'flag' => '🇬🇬',
            ),
            91 => array(
                'id' => 92,
                'name' => 'Guinea',
                'iso3' => 'GIN',
                'iso2' => 'GN',
                'callcode' => '+224',
                'currency' => 'GNF',
                'flag' => '🇬🇳',
            ),
            92 => array(
                'id' => 93,
                'name' => 'Guinea-Bissau',
                'iso3' => 'GNB',
                'iso2' => 'GW',
                'callcode' => '+245',
                'currency' => 'XOF',
                'flag' => '🇬🇼',
            ),
            93 => array(
                'id' => 94,
                'name' => 'Guyana',
                'iso3' => 'GUY',
                'iso2' => 'GY',
                'callcode' => '+592',
                'currency' => 'GYD',
                'flag' => '🇬🇾',
            ),
            94 => array(
                'id' => 95,
                'name' => 'Haiti',
                'iso3' => 'HTI',
                'iso2' => 'HT',
                'callcode' => '+509',
                'currency' => 'HTG',
                'flag' => '🇭🇹',
            ),
            95 => array(
                'id' => 96,
                'name' => 'Heard Island and McDonald Islands',
                'iso3' => 'HMD',
                'iso2' => 'HM',
                'callcode' => '',
                'currency' => 'AUD',
                'flag' => '🇭🇲',
            ),
            96 => array(
                'id' => 97,
                'name' => 'Honduras',
                'iso3' => 'HND',
                'iso2' => 'HN',
                'callcode' => '+504',
                'currency' => 'HNL',
                'flag' => '🇭🇳',
            ),
            97 => array(
                'id' => 98,
                'name' => 'Hong Kong S.A.R.',
                'iso3' => 'HKG',
                'iso2' => 'HK',
                'callcode' => '+852',
                'currency' => 'HKD',
                'flag' => '🇭🇰',
            ),
            98 => array(
                'id' => 99,
                'name' => 'Hungary',
                'iso3' => 'HUN',
                'iso2' => 'HU',
                'callcode' => '+36',
                'currency' => 'HUF',
                'flag' => '🇭🇺',
            ),
            99 => array(
                'id' => 100,
                'name' => 'Iceland',
                'iso3' => 'ISL',
                'iso2' => 'IS',
                'callcode' => '+354',
                'currency' => 'ISK',
                'flag' => '🇮🇸',
            ),
            100 => array(
                'id' => 101,
                'name' => 'India',
                'iso3' => 'IND',
                'iso2' => 'IN',
                'callcode' => '+91',
                'currency' => 'INR',
                'flag' => '🇮🇳',
            ),
            101 => array(
                'id' => 102,
                'name' => 'Indonesia',
                'iso3' => 'IDN',
                'iso2' => 'ID',
                'callcode' => '+62',
                'currency' => 'IDR',
                'flag' => '🇮🇩',
            ),
            102 => array(
                'id' => 103,
                'name' => 'Iran',
                'iso3' => 'IRN',
                'iso2' => 'IR',
                'callcode' => '+98',
                'currency' => 'IRR',
                'flag' => '🇮🇷',
            ),
            103 => array(
                'id' => 104,
                'name' => 'Iraq',
                'iso3' => 'IRQ',
                'iso2' => 'IQ',
                'callcode' => '+964',
                'currency' => 'IQD',
                'flag' => '🇮🇶',
            ),
            104 => array(
                'id' => 105,
                'name' => 'Ireland',
                'iso3' => 'IRL',
                'iso2' => 'IE',
                'callcode' => '+353',
                'currency' => 'EUR',
                'flag' => '🇮🇪',
            ),
            105 => array(
                'id' => 106,
                'name' => 'Israel',
                'iso3' => 'ISR',
                'iso2' => 'IL',
                'callcode' => '+972',
                'currency' => 'ILS',
                'flag' => '🇮🇱',
            ),
            106 => array(
                'id' => 107,
                'name' => 'Italy',
                'iso3' => 'ITA',
                'iso2' => 'IT',
                'callcode' => '+39',
                'currency' => 'EUR',
                'flag' => '🇮🇹',
            ),
            107 => array(
                'id' => 108,
                'name' => 'Jamaica',
                'iso3' => 'JAM',
                'iso2' => 'JM',
                'callcode' => '+1-876',
                'currency' => 'JMD',
                'flag' => '🇯🇲',
            ),
            108 => array(
                'id' => 109,
                'name' => 'Japan',
                'iso3' => 'JPN',
                'iso2' => 'JP',
                'callcode' => '+81',
                'currency' => 'JPY',
                'flag' => '🇯🇵',
            ),
            109 => array(
                'id' => 110,
                'name' => 'Jersey',
                'iso3' => 'JEY',
                'iso2' => 'JE',
                'callcode' => '+44-1534',
                'currency' => 'GBP',
                'flag' => '🇯🇪',
            ),
            110 => array(
                'id' => 111,
                'name' => 'Jordan',
                'iso3' => 'JOR',
                'iso2' => 'JO',
                'callcode' => '+962',
                'currency' => 'JOD',
                'flag' => '🇯🇴',
            ),
            111 => array(
                'id' => 112,
                'name' => 'Kazakhstan',
                'iso3' => 'KAZ',
                'iso2' => 'KZ',
                'callcode' => '+7',
                'currency' => 'KZT',
                'flag' => '🇰🇿',
            ),
            112 => array(
                'id' => 113,
                'name' => 'Kenya',
                'iso3' => 'KEN',
                'iso2' => 'KE',
                'callcode' => '+254',
                'currency' => 'KES',
                'flag' => '🇰🇪',
            ),
            113 => array(
                'id' => 114,
                'name' => 'Kiribati',
                'iso3' => 'KIR',
                'iso2' => 'KI',
                'callcode' => '+686',
                'currency' => 'AUD',
                'flag' => '🇰🇮',
            ),
            114 => array(
                'id' => 115,
                'name' => 'Korea North',
                'iso3' => 'PRK',
                'iso2' => 'KP',
                'callcode' => '+850',
                'currency' => 'KPW',
                'flag' => '🇰🇵',
            ),
            115 => array(
                'id' => 116,
                'name' => 'Korea South',
                'iso3' => 'KOR',
                'iso2' => 'KR',
                'callcode' => '+82',
                'currency' => 'KRW',
                'flag' => '🇰🇷',
            ),
            116 => array(
                'id' => 117,
                'name' => 'Kuwait',
                'iso3' => 'KWT',
                'iso2' => 'KW',
                'callcode' => '+965',
                'currency' => 'KWD',
                'flag' => '🇰🇼',
            ),
            117 => array(
                'id' => 118,
                'name' => 'Kyrgyzstan',
                'iso3' => 'KGZ',
                'iso2' => 'KG',
                'callcode' => '+996',
                'currency' => 'KGS',
                'flag' => '🇰🇬',
            ),
            118 => array(
                'id' => 119,
                'name' => 'Laos',
                'iso3' => 'LAO',
                'iso2' => 'LA',
                'callcode' => '+856',
                'currency' => 'LAK',
                'flag' => '🇱🇦',
            ),
            119 => array(
                'id' => 120,
                'name' => 'Latvia',
                'iso3' => 'LVA',
                'iso2' => 'LV',
                'callcode' => '+371',
                'currency' => 'EUR',
                'flag' => '🇱🇻',
            ),
            121 => array(
                'id' => 122,
                'name' => 'Lesotho',
                'iso3' => 'LSO',
                'iso2' => 'LS',
                'callcode' => '+266',
                'currency' => 'LSL',
                'flag' => '🇱🇸',
            ),
            122 => array(
                'id' => 123,
                'name' => 'Liberia',
                'iso3' => 'LBR',
                'iso2' => 'LR',
                'callcode' => '+231',
                'currency' => 'LRD',
                'flag' => '🇱🇷',
            ),
            123 => array(
                'id' => 124,
                'name' => 'Libya',
                'iso3' => 'LBY',
                'iso2' => 'LY',
                'callcode' => '+218',
                'currency' => 'LYD',
                'flag' => '🇱🇾',
            ),
            124 => array(
                'id' => 125,
                'name' => 'Liechtenstein',
                'iso3' => 'LIE',
                'iso2' => 'LI',
                'callcode' => '+423',
                'currency' => 'CHF',
                'flag' => '🇱🇮',
            ),
            125 => array(
                'id' => 126,
                'name' => 'Lithuania',
                'iso3' => 'LTU',
                'iso2' => 'LT',
                'callcode' => '+370',
                'currency' => 'EUR',
                'flag' => '🇱🇹',
            ),
            126 => array(
                'id' => 127,
                'name' => 'Luxembourg',
                'iso3' => 'LUX',
                'iso2' => 'LU',
                'callcode' => '+352',
                'currency' => 'EUR',
                'flag' => '🇱🇺',
            ),
            127 => array(
                'id' => 128,
                'name' => 'Macau S.A.R.',
                'iso3' => 'MAC',
                'iso2' => 'MO',
                'callcode' => '+853',
                'currency' => 'MOP',
                'flag' => '🇲🇴',
            ),
            128 => array(
                'id' => 129,
                'name' => 'Macedonia',
                'iso3' => 'MKD',
                'iso2' => 'MK',
                'callcode' => '+389',
                'currency' => 'MKD',
                'flag' => '🇲🇰',
            ),
            129 => array(
                'id' => 130,
                'name' => 'Madagascar',
                'iso3' => 'MDG',
                'iso2' => 'MG',
                'callcode' => '+261',
                'currency' => 'MGA',
                'flag' => '🇲🇬',
            ),
            130 => array(
                'id' => 131,
                'name' => 'Malawi',
                'iso3' => 'MWI',
                'iso2' => 'MW',
                'callcode' => '+265',
                'currency' => 'MWK',
                'flag' => '🇲🇼',
            ),
            131 => array(
                'id' => 132,
                'name' => 'Malaysia',
                'iso3' => 'MYS',
                'iso2' => 'MY',
                'callcode' => '+60',
                'currency' => 'MYR',
                'flag' => '🇲🇾',
            ),
            132 => array(
                'id' => 133,
                'name' => 'Maldives',
                'iso3' => 'MDV',
                'iso2' => 'MV',
                'callcode' => '+960',
                'currency' => 'MVR',
                'flag' => '🇲🇻',
            ),
            133 => array(
                'id' => 134,
                'name' => 'Mali',
                'iso3' => 'MLI',
                'iso2' => 'ML',
                'callcode' => '+223',
                'currency' => 'XOF',
                'flag' => '🇲🇱',
            ),
            134 => array(
                'id' => 135,
                'name' => 'Malta',
                'iso3' => 'MLT',
                'iso2' => 'MT',
                'callcode' => '+356',
                'currency' => 'EUR',
                'flag' => '🇲🇹',
            ),
            135 => array(
                'id' => 136,
                'name' => 'Man (Isle of)',
                'iso3' => 'IMN',
                'iso2' => 'IM',
                'callcode' => '+44-1624',
                'currency' => 'GBP',
                'flag' => '🇮🇲',
            ),
            136 => array(
                'id' => 137,
                'name' => 'Marshall Islands',
                'iso3' => 'MHL',
                'iso2' => 'MH',
                'callcode' => '+692',
                'currency' => 'USD',
                'flag' => '🇲🇭',
            ),
            137 => array(
                'id' => 138,
                'name' => 'Martinique',
                'iso3' => 'MTQ',
                'iso2' => 'MQ',
                'callcode' => '+596',
                'currency' => 'EUR',
                'flag' => '🇲🇶',
            ),
            138 => array(
                'id' => 139,
                'name' => 'Mauritania',
                'iso3' => 'MRT',
                'iso2' => 'MR',
                'callcode' => '+222',
                'currency' => 'MRO',
                'flag' => '🇲🇷',
            ),
            139 => array(
                'id' => 140,
                'name' => 'Mauritius',
                'iso3' => 'MUS',
                'iso2' => 'MU',
                'callcode' => '+230',
                'currency' => 'MUR',
                'flag' => '🇲🇺',
            ),
            140 => array(
                'id' => 141,
                'name' => 'Mayotte',
                'iso3' => 'MYT',
                'iso2' => 'YT',
                'callcode' => '+262',
                'currency' => 'EUR',
                'flag' => '🇾🇹',
            ),
            141 => array(
                'id' => 142,
                'name' => 'Mexico',
                'iso3' => 'MEX',
                'iso2' => 'MX',
                'callcode' => '+52',
                'currency' => 'MXN',
                'flag' => '🇲🇽',
            ),
            142 => array(
                'id' => 143,
                'name' => 'Micronesia',
                'iso3' => 'FSM',
                'iso2' => 'FM',
                'callcode' => '+691',
                'currency' => 'USD',
                'flag' => '🇫🇲',
            ),
            143 => array(
                'id' => 144,
                'name' => 'Moldova',
                'iso3' => 'MDA',
                'iso2' => 'MD',
                'callcode' => '+373',
                'currency' => 'MDL',
                'flag' => '🇲🇩',
            ),
            144 => array(
                'id' => 145,
                'name' => 'Monaco',
                'iso3' => 'MCO',
                'iso2' => 'MC',
                'callcode' => '+377',
                'currency' => 'EUR',
                'flag' => '🇲🇨',
            ),
            145 => array(
                'id' => 146,
                'name' => 'Mongolia',
                'iso3' => 'MNG',
                'iso2' => 'MN',
                'callcode' => '+976',
                'currency' => 'MNT',
                'flag' => '🇲🇳',
            ),
            146 => array(
                'id' => 147,
                'name' => 'Montenegro',
                'iso3' => 'MNE',
                'iso2' => 'ME',
                'callcode' => '+382',
                'currency' => 'EUR',
                'flag' => '🇲🇪',
            ),
            147 => array(
                'id' => 148,
                'name' => 'Montserrat',
                'iso3' => 'MSR',
                'iso2' => 'MS',
                'callcode' => '+1-664',
                'currency' => 'XCD',
                'flag' => '🇲🇸',
            ),
            148 => array(
                'id' => 149,
                'name' => 'Morocco',
                'iso3' => 'MAR',
                'iso2' => 'MA',
                'callcode' => '+212',
                'currency' => 'MAD',
                'flag' => '🇲🇦',
            ),
            149 => array(
                'id' => 150,
                'name' => 'Mozambique',
                'iso3' => 'MOZ',
                'iso2' => 'MZ',
                'callcode' => '+258',
                'currency' => 'MZN',
                'flag' => '🇲🇿',
            ),
            150 => array(
                'id' => 151,
                'name' => 'Myanmar',
                'iso3' => 'MMR',
                'iso2' => 'MM',
                'callcode' => '+95',
                'currency' => 'MMK',
                'flag' => '🇲🇲',
            ),
            151 => array(
                'id' => 152,
                'name' => 'Namibia',
                'iso3' => 'NAM',
                'iso2' => 'NA',
                'callcode' => '+264',
                'currency' => 'NAD',
                'flag' => '🇳🇦',
            ),
            152 => array(
                'id' => 153,
                'name' => 'Nauru',
                'iso3' => 'NRU',
                'iso2' => 'NR',
                'callcode' => '+674',
                'currency' => 'AUD',
                'flag' => '🇳🇷',
            ),
            153 => array(
                'id' => 154,
                'name' => 'Nepal',
                'iso3' => 'NPL',
                'iso2' => 'NP',
                'callcode' => '+977',
                'currency' => 'NPR',
                'flag' => '🇳🇵',
            ),
            154 => array(
                'id' => 155,
                'name' => 'Bonaire, Sint Eustatius and Saba',
                'iso3' => 'BES',
                'iso2' => 'BQ',
                'callcode' => '+599',
                'currency' => 'USD',
                'flag' => '🇧🇶',
            ),
            155 => array(
                'id' => 156,
                'name' => 'Netherlands The',
                'iso3' => 'NLD',
                'iso2' => 'NL',
                'callcode' => '+31',
                'currency' => 'EUR',
                'flag' => '🇳🇱',
            ),
            156 => array(
                'id' => 157,
                'name' => 'New Caledonia',
                'iso3' => 'NCL',
                'iso2' => 'NC',
                'callcode' => '+687',
                'currency' => 'XPF',
                'flag' => '🇳🇨',
            ),
            157 => array(
                'id' => 158,
                'name' => 'New Zealand',
                'iso3' => 'NZL',
                'iso2' => 'NZ',
                'callcode' => '+64',
                'currency' => 'NZD',
                'flag' => '🇳🇿',
            ),
            158 => array(
                'id' => 159,
                'name' => 'Nicaragua',
                'iso3' => 'NIC',
                'iso2' => 'NI',
                'callcode' => '+505',
                'currency' => 'NIO',
                'flag' => '🇳🇮',
            ),
            159 => array(
                'id' => 160,
                'name' => 'Niger',
                'iso3' => 'NER',
                'iso2' => 'NE',
                'callcode' => '+227',
                'currency' => 'XOF',
                'flag' => '🇳🇪',
            ),
            160 => array(
                'id' => 161,
                'name' => 'Nigeria',
                'iso3' => 'NGA',
                'iso2' => 'NG',
                'callcode' => '+234',
                'currency' => 'NGN',
                'flag' => '🇳🇬',
            ),
            161 => array(
                'id' => 162,
                'name' => 'Niue',
                'iso3' => 'NIU',
                'iso2' => 'NU',
                'callcode' => '+683',
                'currency' => 'NZD',
                'flag' => '🇳🇺',
            ),
            162 => array(
                'id' => 163,
                'name' => 'Norfolk Island',
                'iso3' => 'NFK',
                'iso2' => 'NF',
                'callcode' => '+672',
                'currency' => 'AUD',
                'flag' => '🇳🇫',
            ),
            163 => array(
                'id' => 164,
                'name' => 'Northern Mariana Islands',
                'iso3' => 'MNP',
                'iso2' => 'MP',
                'callcode' => '+1-670',
                'currency' => 'USD',
                'flag' => '🇲🇵',
            ),
            164 => array(
                'id' => 165,
                'name' => 'Norway',
                'iso3' => 'NOR',
                'iso2' => 'NO',
                'callcode' => '+47',
                'currency' => 'NOK',
                'flag' => '🇳🇴',
            ),
            165 => array(
                'id' => 166,
                'name' => 'Oman',
                'iso3' => 'OMN',
                'iso2' => 'OM',
                'callcode' => '+968',
                'currency' => 'OMR',
                'flag' => '🇴🇲',
            ),
            166 => array(
                'id' => 167,
                'name' => 'Pakistan',
                'iso3' => 'PAK',
                'iso2' => 'PK',
                'callcode' => '+92',
                'currency' => 'PKR',
                'flag' => '🇵🇰',
            ),
            167 => array(
                'id' => 168,
                'name' => 'Palau',
                'iso3' => 'PLW',
                'iso2' => 'PW',
                'callcode' => '+680',
                'currency' => 'USD',
                'flag' => '🇵🇼',
            ),
            168 => array(
                'id' => 169,
                'name' => 'Palestinian Territory Occupied',
                'iso3' => 'PSE',
                'iso2' => 'PS',
                'callcode' => '+970',
                'currency' => 'ILS',
                'flag' => '🇵🇸',
            ),
            169 => array(
                'id' => 170,
                'name' => 'Panama',
                'iso3' => 'PAN',
                'iso2' => 'PA',
                'callcode' => '+507',
                'currency' => 'PAB',
                'flag' => '🇵🇦',
            ),
            170 => array(
                'id' => 171,
                'name' => 'Papua new Guinea',
                'iso3' => 'PNG',
                'iso2' => 'PG',
                'callcode' => '+675',
                'currency' => 'PGK',
                'flag' => '🇵🇬',
            ),
            171 => array(
                'id' => 172,
                'name' => 'Paraguay',
                'iso3' => 'PRY',
                'iso2' => 'PY',
                'callcode' => '+595',
                'currency' => 'PYG',
                'flag' => '🇵🇾',
            ),
            172 => array(
                'id' => 173,
                'name' => 'Peru',
                'iso3' => 'PER',
                'iso2' => 'PE',
                'callcode' => '+51',
                'currency' => 'PEN',
                'flag' => '🇵🇪',
            ),
            173 => array(
                'id' => 174,
                'name' => 'Philippines',
                'iso3' => 'PHL',
                'iso2' => 'PH',
                'callcode' => '+63',
                'currency' => 'PHP',
                'flag' => '🇵🇭',
            ),
            174 => array(
                'id' => 175,
                'name' => 'Pitcairn Island',
                'iso3' => 'PCN',
                'iso2' => 'PN',
                'callcode' => '+870',
                'currency' => 'NZD',
                'flag' => '🇵🇳',
            ),
            175 => array(
                'id' => 176,
                'name' => 'Poland',
                'iso3' => 'POL',
                'iso2' => 'PL',
                'callcode' => '+48',
                'currency' => 'PLN',
                'flag' => '🇵🇱',
            ),
            176 => array(
                'id' => 177,
                'name' => 'Portugal',
                'iso3' => 'PRT',
                'iso2' => 'PT',
                'callcode' => '+351',
                'currency' => 'EUR',
                'flag' => '🇵🇹',
            ),
            177 => array(
                'id' => 178,
                'name' => 'Puerto Rico',
                'iso3' => 'PRI',
                'iso2' => 'PR',
                'callcode' => '+1-787 and 1-939',
                'currency' => 'USD',
                'flag' => '🇵🇷',
            ),
            178 => array(
                'id' => 179,
                'name' => 'Qatar',
                'iso3' => 'QAT',
                'iso2' => 'QA',
                'callcode' => '+974',
                'currency' => 'QAR',
                'flag' => '🇶🇦',
            ),
            179 => array(
                'id' => 180,
                'name' => 'Reunion',
                'iso3' => 'REU',
                'iso2' => 'RE',
                'callcode' => '+262',
                'currency' => 'EUR',
                'flag' => '🇷🇪',
            ),
            180 => array(
                'id' => 181,
                'name' => 'Romania',
                'iso3' => 'ROU',
                'iso2' => 'RO',
                'callcode' => '+40',
                'currency' => 'RON',
                'flag' => '🇷🇴',
            ),
            181 => array(
                'id' => 182,
                'name' => 'Russia',
                'iso3' => 'RUS',
                'iso2' => 'RU',
                'callcode' => '+7',
                'currency' => 'RUB',
                'flag' => '🇷🇺',
            ),
            182 => array(
                'id' => 183,
                'name' => 'Rwanda',
                'iso3' => 'RWA',
                'iso2' => 'RW',
                'callcode' => '+250',
                'currency' => 'RWF',
                'flag' => '🇷🇼',
            ),
            183 => array(
                'id' => 184,
                'name' => 'Saint Helena',
                'iso3' => 'SHN',
                'iso2' => 'SH',
                'callcode' => '+290',
                'currency' => 'SHP',
                'flag' => '🇸🇭',
            ),
            184 => array(
                'id' => 185,
                'name' => 'Saint Kitts And Nevis',
                'iso3' => 'KNA',
                'iso2' => 'KN',
                'callcode' => '+1-869',
                'currency' => 'XCD',
                'flag' => '🇰🇳',
            ),
            185 => array(
                'id' => 186,
                'name' => 'Saint Lucia',
                'iso3' => 'LCA',
                'iso2' => 'LC',
                'callcode' => '+1-758',
                'currency' => 'XCD',
                'flag' => '🇱🇨',
            ),
            186 => array(
                'id' => 187,
                'name' => 'Saint Pierre and Miquelon',
                'iso3' => 'SPM',
                'iso2' => 'PM',
                'callcode' => '+508',
                'currency' => 'EUR',
                'flag' => '🇵🇲',
            ),
            187 => array(
                'id' => 188,
                'name' => 'Saint Vincent And The Grenadines',
                'iso3' => 'VCT',
                'iso2' => 'VC',
                'callcode' => '+1-784',
                'currency' => 'XCD',
                'flag' => '🇻🇨',
            ),
            188 => array(
                'id' => 189,
                'name' => 'Saint-Barthelemy',
                'iso3' => 'BLM',
                'iso2' => 'BL',
                'callcode' => '+590',
                'currency' => 'EUR',
                'flag' => '🇧🇱',
            ),
            189 => array(
                'id' => 190,
                'name' => 'Saint-Martin (French part)',
                'iso3' => 'MAF',
                'iso2' => 'MF',
                'callcode' => '+590',
                'currency' => 'EUR',
                'flag' => '🇲🇫',
            ),
            190 => array(
                'id' => 191,
                'name' => 'Samoa',
                'iso3' => 'WSM',
                'iso2' => 'WS',
                'callcode' => '+685',
                'currency' => 'WST',
                'flag' => '🇼🇸',
            ),
            191 => array(
                'id' => 192,
                'name' => 'San Marino',
                'iso3' => 'SMR',
                'iso2' => 'SM',
                'callcode' => '+378',
                'currency' => 'EUR',
                'flag' => '🇸🇲',
            ),
            192 => array(
                'id' => 193,
                'name' => 'Sao Tome and Principe',
                'iso3' => 'STP',
                'iso2' => 'ST',
                'callcode' => '+239',
                'currency' => 'STD',
                'flag' => '🇸🇹',
            ),
            193 => array(
                'id' => 194,
                'name' => 'Saudi Arabia',
                'iso3' => 'SAU',
                'iso2' => 'SA',
                'callcode' => '+966',
                'currency' => 'SAR',
                'flag' => '🇸🇦',
            ),
            194 => array(
                'id' => 195,
                'name' => 'Senegal',
                'iso3' => 'SEN',
                'iso2' => 'SN',
                'callcode' => '+221',
                'currency' => 'XOF',
                'flag' => '🇸🇳',
            ),
            195 => array(
                'id' => 196,
                'name' => 'Serbia',
                'iso3' => 'SRB',
                'iso2' => 'RS',
                'callcode' => '+381',
                'currency' => 'RSD',
                'flag' => '🇷🇸',
            ),
            196 => array(
                'id' => 197,
                'name' => 'Seychelles',
                'iso3' => 'SYC',
                'iso2' => 'SC',
                'callcode' => '+248',
                'currency' => 'SCR',
                'flag' => '🇸🇨',
            ),
            197 => array(
                'id' => 198,
                'name' => 'Sierra Leone',
                'iso3' => 'SLE',
                'iso2' => 'SL',
                'callcode' => '+232',
                'currency' => 'SLL',
                'flag' => '🇸🇱',
            ),
            198 => array(
                'id' => 199,
                'name' => 'Singapore',
                'iso3' => 'SGP',
                'iso2' => 'SG',
                'callcode' => '+65',
                'currency' => 'SGD',
                'flag' => '🇸🇬',
            ),
            199 => array(
                'id' => 200,
                'name' => 'Slovakia',
                'iso3' => 'SVK',
                'iso2' => 'SK',
                'callcode' => '+421',
                'currency' => 'EUR',
                'flag' => '🇸🇰',
            ),
            200 => array(
                'id' => 201,
                'name' => 'Slovenia',
                'iso3' => 'SVN',
                'iso2' => 'SI',
                'callcode' => '+386',
                'currency' => 'EUR',
                'flag' => '🇸🇮',
            ),
            201 => array(
                'id' => 202,
                'name' => 'Solomon Islands',
                'iso3' => 'SLB',
                'iso2' => 'SB',
                'callcode' => '+677',
                'currency' => 'SBD',
                'flag' => '🇸🇧',
            ),
            202 => array(
                'id' => 203,
                'name' => 'Somalia',
                'iso3' => 'SOM',
                'iso2' => 'SO',
                'callcode' => '+252',
                'currency' => 'SOS',
                'flag' => '🇸🇴',
            ),
            203 => array(
                'id' => 204,
                'name' => 'South Africa',
                'iso3' => 'ZAF',
                'iso2' => 'ZA',
                'callcode' => '+27',
                'currency' => 'ZAR',
                'flag' => '🇿🇦',
            ),
            204 => array(
                'id' => 205,
                'name' => 'South Georgia',
                'iso3' => 'SGS',
                'iso2' => 'GS',
                'callcode' => '',
                'currency' => 'GBP',
                'flag' => '🇬🇸',
            ),
            205 => array(
                'id' => 206,
                'name' => 'South Sudan',
                'iso3' => 'SSD',
                'iso2' => 'SS',
                'callcode' => '+211',
                'currency' => 'SSP',
                'flag' => '🇸🇸',
            ),
            206 => array(
                'id' => 207,
                'name' => 'Spain',
                'iso3' => 'ESP',
                'iso2' => 'ES',
                'callcode' => '+34',
                'currency' => 'EUR',
                'flag' => '🇪🇸',
            ),
            207 => array(
                'id' => 208,
                'name' => 'Sri Lanka',
                'iso3' => 'LKA',
                'iso2' => 'LK',
                'callcode' => '+94',
                'currency' => 'LKR',
                'flag' => '🇱🇰',
            ),
            208 => array(
                'id' => 209,
                'name' => 'Sudan',
                'iso3' => 'SDN',
                'iso2' => 'SD',
                'callcode' => '+249',
                'currency' => 'SDG',
                'flag' => '🇸🇩',
            ),
            209 => array(
                'id' => 210,
                'name' => 'Suriname',
                'iso3' => 'SUR',
                'iso2' => 'SR',
                'callcode' => '+597',
                'currency' => 'SRD',
                'flag' => '🇸🇷',
            ),
            210 => array(
                'id' => 211,
                'name' => 'Svalbard And Jan Mayen Islands',
                'iso3' => 'SJM',
                'iso2' => 'SJ',
                'callcode' => '+47',
                'currency' => 'NOK',
                'flag' => '🇸🇯',
            ),
            211 => [
                'id' => 212,
                'name' => 'Swaziland',
                'iso3' => 'SWZ',
                'iso2' => 'SZ',
                'callcode' => '+268',
                'currency' => 'SZL',
                'flag' => '🇸🇿',
            ],
            212 => [
                'id' => 213,
                'name' => 'Sweden',
                'iso3' => 'SWE',
                'iso2' => 'SE',
                'callcode' => '+46',
                'currency' => 'SEK',
                'flag' => '🇸🇪',
            ],
            213 => [
                'id' => 214,
                'name' => 'Switzerland',
                'iso3' => 'CHE',
                'iso2' => 'CH',
                'callcode' => '+41',
                'currency' => 'CHF',
                'flag' => '🇨🇭',
            ],
            214 => [
                'id' => 215,
                'name' => 'Syria',
                'iso3' => 'SYR',
                'iso2' => 'SY',
                'callcode' => '+963',
                'currency' => 'SYP',
                'flag' => '🇸🇾',
            ],
            215 => [
                'id' => 216,
                'name' => 'Taiwan',
                'iso3' => 'TWN',
                'iso2' => 'TW',
                'callcode' => '+886',
                'currency' => 'TWD',
                'flag' => '🇹🇼',
            ],
            216 => [
                'id' => 217,
                'name' => 'Tajikistan',
                'iso3' => 'TJK',
                'iso2' => 'TJ',
                'callcode' => '+992',
                'currency' => 'TJS',
                'flag' => '🇹🇯',
            ],
            217 => [
                'id' => 218,
                'name' => 'Tanzania',
                'iso3' => 'TZA',
                'iso2' => 'TZ',
                'callcode' => '+255',
                'currency' => 'TZS',
                'flag' => '🇹🇿',
            ],
            218 => [
                'id' => 219,
                'name' => 'Thailand',
                'iso3' => 'THA',
                'iso2' => 'TH',
                'callcode' => '+66',
                'currency' => 'THB',
                'flag' => '🇹🇭',
            ],
            219 => [
                'id' => 220,
                'name' => 'Togo',
                'iso3' => 'TGO',
                'iso2' => 'TG',
                'callcode' => '+228',
                'currency' => 'XOF',
                'flag' => '🇹🇬',
            ],
            220 => [
                'id' => 221,
                'name' => 'Tokelau',
                'iso3' => 'TKL',
                'iso2' => 'TK',
                'callcode' => '+690',
                'currency' => 'NZD',
                'flag' => '🇹🇰',
            ],
            221 => [
                'id' => 222,
                'name' => 'Tonga',
                'iso3' => 'TON',
                'iso2' => 'TO',
                'callcode' => '+676',
                'currency' => 'TOP',
                'flag' => '🇹🇴',
            ],
            222 => [
                'id' => 223,
                'name' => 'Trinidad And Tobago',
                'iso3' => 'TTO',
                'iso2' => 'TT',
                'callcode' => '+1-868',
                'currency' => 'TTD',
                'flag' => '🇹🇹',
            ],
            223 => [
                'id' => 224,
                'name' => 'Tunisia',
                'iso3' => 'TUN',
                'iso2' => 'TN',
                'callcode' => '+216',
                'currency' => 'TND',
                'flag' => '🇹🇳',
            ],
            224 => [
                'id' => 225,
                'name' => 'Turkey',
                'iso3' => 'TUR',
                'iso2' => 'TR',
                'callcode' => '+90',
                'currency' => 'TRY',
                'flag' => '🇹🇷',
            ],
            225 => [
                'id' => 226,
                'name' => 'Turkmenistan',
                'iso3' => 'TKM',
                'iso2' => 'TM',
                'callcode' => '+993',
                'currency' => 'TMT',
                'flag' => '🇹🇲',
            ],
            226 => [
                'id' => 227,
                'name' => 'Turks And Caicos Islands',
                'iso3' => 'TCA',
                'iso2' => 'TC',
                'callcode' => '+1-649',
                'currency' => 'USD',
                'flag' => '🇹🇨',
            ],
            227 => [
                'id' => 228,
                'name' => 'Tuvalu',
                'iso3' => 'TUV',
                'iso2' => 'TV',
                'callcode' => '+688',
                'currency' => 'AUD',
                'flag' => '🇹🇻',
            ],
            228 => [
                'id' => 229,
                'name' => 'Uganda',
                'iso3' => 'UGA',
                'iso2' => 'UG',
                'callcode' => '+256',
                'currency' => 'UGX',
                'flag' => '🇺🇬',
            ],
            229 => [
                'id' => 230,
                'name' => 'Ukraine',
                'iso3' => 'UKR',
                'iso2' => 'UA',
                'callcode' => '+380',
                'currency' => 'UAH',
                'flag' => '🇺🇦',
            ],
            230 => [
                'id' => 231,
                'name' => 'United Arab Emirates',
                'iso3' => 'ARE',
                'iso2' => 'AE',
                'callcode' => '+971',
                'currency' => 'AED',
                'flag' => '🇦🇪',
            ],
            231 => [
                'id' => 232,
                'name' => 'United Kingdom',
                'iso3' => 'GBR',
                'iso2' => 'GB',
                'callcode' => '+44',
                'currency' => 'GBP',
                'flag' => '🇬🇧',
            ],
            232 => [
                'id' => 233,
                'name' => 'United States',
                'iso3' => 'USA',
                'iso2' => 'US',
                'callcode' => '+1',
                'currency' => 'USD',
                'flag' => '🇺🇸',
            ],
            233 => [
                'id' => 234,
                'name' => 'United States Minor Outlying Islands',
                'iso3' => 'UMI',
                'iso2' => 'UM',
                'callcode' => '+1',
                'currency' => 'USD',
                'flag' => '🇺🇲',
            ],
            234 => [
                'id' => 235,
                'name' => 'Uruguay',
                'iso3' => 'URY',
                'iso2' => 'UY',
                'callcode' => '+598',
                'currency' => 'UYU',
                'flag' => '🇺🇾',
            ],
            235 => [
                'id' => 236,
                'name' => 'Uzbekistan',
                'iso3' => 'UZB',
                'iso2' => 'UZ',
                'callcode' => '+998',
                'currency' => 'UZS',
                'flag' => '🇺🇿',
            ],
            236 => [
                'id' => 237,
                'name' => 'Vanuatu',
                'iso3' => 'VUT',
                'iso2' => 'VU',
                'callcode' => '+678',
                'currency' => 'VUV',
                'flag' => '🇻🇺',
            ],
            237 => [
                'id' => 238,
                'name' => 'Vatican City State (Holy See)',
                'iso3' => 'VAT',
                'iso2' => 'VA',
                'callcode' => '+379',
                'currency' => 'EUR',
                'flag' => '🇻🇦',
            ],
            238 => [
                'id' => 239,
                'name' => 'Venezuela',
                'iso3' => 'VEN',
                'iso2' => 'VE',
                'callcode' => '+58',
                'currency' => 'VEF',
                'flag' => '🇻🇪',
            ],
            239 => [
                'id' => 240,
                'name' => 'Vietnam',
                'iso3' => 'VNM',
                'iso2' => 'VN',
                'callcode' => '+84',
                'currency' => 'VND',
                'flag' => '🇻🇳',
            ],
            240 => [
                'id' => 241,
                'name' => 'Virgin Islands (British)',
                'iso3' => 'VGB',
                'iso2' => 'VG',
                'callcode' => '+1-284',
                'currency' => 'USD',
                'flag' => '🇻🇬',
            ],
            241 => [
                'id' => 242,
                'name' => 'Virgin Islands (US)',
                'iso3' => 'VIR',
                'iso2' => 'VI',
                'callcode' => '+1-340',
                'currency' => 'USD',
                'flag' => '🇻🇮',
            ],
            242 => [
                'id' => 243,
                'name' => 'Wallis And Futuna Islands',
                'iso3' => 'WLF',
                'iso2' => 'WF',
                'callcode' => '+681',
                'currency' => 'XPF',
                'flag' => '🇼🇫',
            ],
            243 => [
                'id' => 244,
                'name' => 'Western Sahara',
                'iso3' => 'ESH',
                'iso2' => 'EH',
                'callcode' => '+212',
                'currency' => 'MAD',
                'flag' => '🇪🇭',
            ],
            244 => [
                'id' => 245,
                'name' => 'Yemen',
                'iso3' => 'YEM',
                'iso2' => 'YE',
                'callcode' => '+967',
                'currency' => 'YER',
                'flag' => '🇾🇪',
            ],
            245 => [
                'id' => 246,
                'name' => 'Zambia',
                'iso3' => 'ZMB',
                'iso2' => 'ZM',
                'callcode' => '+260',
                'currency' => 'ZMW',
                'flag' => '🇿🇲',
            ],
            246 => [
                'id' => 247,
                'name' => 'Zimbabwe',
                'iso3' => 'ZWE',
                'iso2' => 'ZW',
                'callcode' => '+263',
                'currency' => 'ZWL',
                'flag' => '🇿🇼',
            ],
            247 => [
                'id' => 248,
                'name' => 'Kosovo',
                'iso3' => 'XKX',
                'iso2' => 'XK',
                'callcode' => '+383',
                'currency' => 'EUR',
                'flag' => '🇽🇰',
            ],
            248 => [
                'id' => 249,
                'name' => 'Curaçao',
                'iso3' => 'CUW',
                'iso2' => 'CW',
                'callcode' => '+599',
                'currency' => 'ANG',
                'flag' => '🇨🇼',
            ],
            249 => [
                'id' => 250,
                'name' => 'Sint Maarten (Dutch part)',
                'iso3' => 'SXM',
                'iso2' => 'SX',
                'callcode' => '+1721',
                'currency' => 'ANG',
                'flag' => '🇸🇽',
            ],
        ));

    }
}
