<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class HomePageMM extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        "slider_title_1",
        "slider_title_2",
        "slider_title_3",
        "slider_title_4",
        "slider_title_5",
        "title_1",
        "title_2",
        "title_3",
        "title_4",
        "title_5",
        "title_6",
        "title_7",
        "title_8",
        "title_9",
        "title_10",
        "title_11",
        "title_12",
        "title_13",
        "title_14",
        "title_15",
        "title_16",
        "title_17",
        "title_18",
        "title_19",
        "title_20",
        "slider_content_1",
        "slider_content_2",
        "slider_content_3",
        "slider_content_4",
        "slider_content_5",
        "content_1",
        "content_2",
        "content_3",
        "content_4",
        "content_5",
        "content_6",
        "content_7",
        "content_8",
        "content_9",
        "content_10",
        "content_11",
        "content_12",
        "content_13",
        "content_14",
        "content_15",
        "content_16",
        "content_17",
        "content_18",
        "content_19",
        "content_20",
        "slider_image_1",
        "slider_image_2",
        "slider_image_3",
        "slider_image_4",
        "slider_image_5",
        "image_1",
        "image_2",
        "image_3",
        "image_4",
        "image_5",
        "image_6",
        "image_7",
        "image_8",
        "image_9",
        "image_10",
        "image_11",
        "image_12",
        "image_13",
        "image_14",
        "image_15",
        "image_16",
        "image_17",
        "image_18",
        "image_19",
        "image_20",
        "image_m_1",
        "image_m_2",
        "image_m_3",
        "image_m_4",
        "image_m_5",
        "image_m_6",
        "image_m_7",
        "image_m_8",
        "image_m_9",
        "image_m_10",
    ];
}
